### PR TITLE
refactor for latest react-native + es6

### PR DESCRIPTION
**Pull request by skylinezum**
- refactor for latest react-native
- change to es6

### CODE REVIEW

**Comment by omulet** [comment]
@skylinezum, 

Everything seams valid at the first look, but I'll need to test before merging. Probably over the weekend.

Thanks for your input

**Comment by omulet** [comment]
@skylinezum 

There's a bug in your code that prevents me for merging. We don't want the root of our menu to map on radial positions when the menu is opened. The root needs to stay in place (circle center) until I start moving towards an option.  That's why we attach the panHandlers only to item_anims[0] (our root): `handlers = j > 0 ? {} : this.state.itemPanResponder.panHandlers`

So to fix this, after we generateRadialPositions, we need to inject another spot at 0,0.

After:
```
let initial_spots = generateRadialPositions(
      children.length - 1,
      this.props.menuRadius,
      this.props.spreadAngle,
      this.props.startAngle
    );
```

Add this:
```
initial_spots.unshift({x: 0, y: 0});
```

Once you fix this, you can submit a new PR and I'll merge.

Thanks

**Comment by skylinezum** [comment]
@omulet 

Ok, changes made. :)

**Comment by omulet** [comment]
Merged in master. Thanks again

**Pull request merged**
